# Generated by Django 5.1.2 on 2024-10-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_brand_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='default', max_length=10),
        ),
    ]
