# Generated by Django 5.1.2 on 2024-11-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
